version: '3'
services:
  app:
    container_name: zerwego-api
    restart: always
    build: .
    command: npm run build
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - .:/home/app/appDir
      - /home/app/appDir/node_modules
  mongo:
    container_name: zerwego-mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
        - ./data/db:/data/db
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "8080:8080"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config